# アプリケーション用ベースマニフェスト
apiVersion: managed.msp.sbopsv/v1alpha1
kind: Application
metadata:
  name: backend  # name だけで namespace を指定しない
spec:
  chart:
    name: basic-deployment
    version: x
  settings:
    image:
      repository: kanboard/kanboard
      pullPolicy: IfNotPresent
      tag: "latest"
    network:
      service:
        ports:
          - name: backend
            containerPort: 80
            servicePort: 80
    mountSecrets:
      - remoteRef:
          key: rdb-admin
        property: password
        env: DB_PASSWORD
    mountConfigmaps:
     - name: rdb-env
       key: DB_NAME
       env: DB_NAME
     - name: rdb-env
       key: DB_HOSTNAME
       env: DB_HOSTNAME
     - name: rdb-env
       key: DB_USERNAME
       env: DB_USERNAME
     - name: rdb-env
       key: DB_DRIVER
       env: DB_DRIVER
    timeout: 10m
