apiVersion: managed.msp.sbopsv/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: backend
spec:
  chart:
    name: rdb
    version: x
  settings:
    databaseType: mysql
    instance:
      name: mysql
      machineType: db.t3.micro
      location: ap-northeast-1
      engineVersion: "8.0"
      storage:
        type: gp2
        size: 20
      backup:
        retentionPeriod: 7
        aws:
          startTime: 16:00
          endTime: 17:00
      availability:
        highAvailability: false
    network:
      aws:
        subnets: []
    databases:
      - app1
    users: []
