# アプリケーション用ベースマニフェスト
apiVersion: managed.msp.sbopsv/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: app1
spec:
  chart:
    name: basic-deployment
    version: x
  settings:
    image:
      repository: kanboard/kanboard
      pullPolicy: IfNotPresent
      tag: "latest"
    network:
      domain: app1.prd.example.com
      service:
        ports:
          - name: frontend
            containerPort: 80
            servicePort: 80
    timeout: 10m
